

Text1=[
"INSERT INTO \"commodities\" VALUES ('Offshore','p','#Victor Ocean 2021');",
"INSERT INTO \"technologies\" VALUES ('GeneralOcean','p','electric','#Victor Ocean 2021','Offshore');",
"INSERT INTO \"Efficiency\" VALUES ('Offshore','GeneralOcean',2017,'ELCRNWB',1.0,' ');",
"INSERT INTO \"Efficiency\" VALUES ('Offshore','GeneralOcean',2020,'ELCRNWB',1.0,' ');",
"INSERT INTO \"Efficiency\" VALUES ('Offshore','GeneralOcean',2025,'ELCRNWB',1.0,' ');",
"INSERT INTO \"Efficiency\" VALUES ('Offshore','GeneralOcean',2030,'ELCRNWB',1.0,' ');",
"INSERT INTO \"Efficiency\" VALUES ('Offshore','GeneralOcean',2035,'ELCRNWB',1.0,' ');",
"INSERT INTO \"CapacityToActivity\" VALUES ('GeneralOcean',8760.0,'#GW to GWh');",
"INSERT INTO \"CostVariable\" VALUES (2017,'GeneralOcean',2017,0.0,'#M$/GWh','');",
"INSERT INTO \"CostVariable\" VALUES (2020,'GeneralOcean',2017,0.0,'#M$/GWh','');",
"INSERT INTO \"CostVariable\" VALUES (2025,'GeneralOcean',2017,0.0,'#M$/GWh','');",
"INSERT INTO \"CostVariable\" VALUES (2030,'GeneralOcean',2017,0.0,'#M$/GWh','');",
"INSERT INTO \"CostVariable\" VALUES (2020,'GeneralOcean',2020,0.0,'#M$/GWh','');",
"INSERT INTO \"CostVariable\" VALUES (2025,'GeneralOcean',2020,0.0,'#M$/GWh','');",
"INSERT INTO \"CostVariable\" VALUES (2030,'GeneralOcean',2020,0.0,'#M$/GWh','');",
"INSERT INTO \"CostVariable\" VALUES (2035,'GeneralOcean',2020,0.0,'#M$/GWh','');",
"INSERT INTO \"CostVariable\" VALUES (2025,'GeneralOcean',2025,0.0,'#M$/GWh','');",
"INSERT INTO \"CostVariable\" VALUES (2030,'GeneralOcean',2025,0.0,'#M$/GWh','');",
"INSERT INTO \"CostVariable\" VALUES (2035,'GeneralOcean',2025,0.0,'#M$/GWh','');",
"INSERT INTO \"CostVariable\" VALUES (2030,'GeneralOcean',2030,0.0,'#M$/GWh','');",
"INSERT INTO \"CostVariable\" VALUES (2035,'GeneralOcean',2030,0.0,'#M$/GWh','');",
"INSERT INTO \"CostVariable\" VALUES (2035,'GeneralOcean',2035,0.0,'#M$/GWh','');",
"INSERT INTO \"LifetimeTech\" VALUES ('GeneralOcean',30.0,' ');",
"INSERT INTO \"LifetimeLoanTech\" VALUES ('GeneralOcean',30.0,'');",
"INSERT INTO \"CapacityCredit\" VALUES('GeneralOcean',0.4,'#Victor Ocean 2021');",
"INSERT INTO \"DiscountRate\" VALUES('GeneralOcean',2017,0.113,'#Victor Ocean 2021');",
"INSERT INTO \"DiscountRate\" VALUES('GeneralOcean',2020,0.113,'#Victor Ocean 2021');",
"INSERT INTO \"DiscountRate\" VALUES('GeneralOcean',2025,0.113,'#Victor Ocean 2021');",
"INSERT INTO \"DiscountRate\" VALUES('GeneralOcean',2030,0.113,'#Victor Ocean 2021');",
"INSERT INTO \"DiscountRate\" VALUES('GeneralOcean',2035,0.113,'#Victor Ocean 2021');"]

Text_CF_L=[
"INSERT INTO \"CapacityFactorTech\" VALUES ('s001','tod01','GeneralOcean',",
"INSERT INTO \"CapacityFactorTech\" VALUES ('s001','tod02','GeneralOcean',",
"INSERT INTO \"CapacityFactorTech\" VALUES ('s001','tod03','GeneralOcean',",
"INSERT INTO \"CapacityFactorTech\" VALUES ('s001','tod04','GeneralOcean',",
"INSERT INTO \"CapacityFactorTech\" VALUES ('s001','tod05','GeneralOcean',",
"INSERT INTO \"CapacityFactorTech\" VALUES ('s001','tod06','GeneralOcean',",
"INSERT INTO \"CapacityFactorTech\" VALUES ('s001','tod07','GeneralOcean',",
"INSERT INTO \"CapacityFactorTech\" VALUES ('s001','tod08','GeneralOcean',",
"INSERT INTO \"CapacityFactorTech\" VALUES ('s001','tod09','GeneralOcean',",
"INSERT INTO \"CapacityFactorTech\" VALUES ('s001','tod10','GeneralOcean',",
"INSERT INTO \"CapacityFactorTech\" VALUES ('s001','tod11','GeneralOcean',",
"INSERT INTO \"CapacityFactorTech\" VALUES ('s001','tod12','GeneralOcean',",
"INSERT INTO \"CapacityFactorTech\" VALUES ('s001','tod13','GeneralOcean',",
"INSERT INTO \"CapacityFactorTech\" VALUES ('s001','tod14','GeneralOcean',",
"INSERT INTO \"CapacityFactorTech\" VALUES ('s001','tod15','GeneralOcean',",
"INSERT INTO \"CapacityFactorTech\" VALUES ('s001','tod16','GeneralOcean',",
"INSERT INTO \"CapacityFactorTech\" VALUES ('s001','tod17','GeneralOcean',",
"INSERT INTO \"CapacityFactorTech\" VALUES ('s001','tod18','GeneralOcean',",
"INSERT INTO \"CapacityFactorTech\" VALUES ('s001','tod19','GeneralOcean',",
"INSERT INTO \"CapacityFactorTech\" VALUES ('s001','tod20','GeneralOcean',",
"INSERT INTO \"CapacityFactorTech\" VALUES ('s001','tod21','GeneralOcean',",
"INSERT INTO \"CapacityFactorTech\" VALUES ('s001','tod22','GeneralOcean',",
"INSERT INTO \"CapacityFactorTech\" VALUES ('s001','tod23','GeneralOcean',",
"INSERT INTO \"CapacityFactorTech\" VALUES ('s001','tod24','GeneralOcean',",
"INSERT INTO \"CapacityFactorTech\" VALUES ('s002','tod01','GeneralOcean',",
"INSERT INTO \"CapacityFactorTech\" VALUES ('s002','tod02','GeneralOcean',",
"INSERT INTO \"CapacityFactorTech\" VALUES ('s002','tod03','GeneralOcean',",
"INSERT INTO \"CapacityFactorTech\" VALUES ('s002','tod04','GeneralOcean',",
"INSERT INTO \"CapacityFactorTech\" VALUES ('s002','tod05','GeneralOcean',",
"INSERT INTO \"CapacityFactorTech\" VALUES ('s002','tod06','GeneralOcean',",
"INSERT INTO \"CapacityFactorTech\" VALUES ('s002','tod07','GeneralOcean',",
"INSERT INTO \"CapacityFactorTech\" VALUES ('s002','tod08','GeneralOcean',",
"INSERT INTO \"CapacityFactorTech\" VALUES ('s002','tod09','GeneralOcean',",
"INSERT INTO \"CapacityFactorTech\" VALUES ('s002','tod10','GeneralOcean',",
"INSERT INTO \"CapacityFactorTech\" VALUES ('s002','tod11','GeneralOcean',",
"INSERT INTO \"CapacityFactorTech\" VALUES ('s002','tod12','GeneralOcean',",
"INSERT INTO \"CapacityFactorTech\" VALUES ('s002','tod13','GeneralOcean',",
"INSERT INTO \"CapacityFactorTech\" VALUES ('s002','tod14','GeneralOcean',",
"INSERT INTO \"CapacityFactorTech\" VALUES ('s002','tod15','GeneralOcean',",
"INSERT INTO \"CapacityFactorTech\" VALUES ('s002','tod16','GeneralOcean',",
"INSERT INTO \"CapacityFactorTech\" VALUES ('s002','tod17','GeneralOcean',",
"INSERT INTO \"CapacityFactorTech\" VALUES ('s002','tod18','GeneralOcean',",
"INSERT INTO \"CapacityFactorTech\" VALUES ('s002','tod19','GeneralOcean',",
"INSERT INTO \"CapacityFactorTech\" VALUES ('s002','tod20','GeneralOcean',",
"INSERT INTO \"CapacityFactorTech\" VALUES ('s002','tod21','GeneralOcean',",
"INSERT INTO \"CapacityFactorTech\" VALUES ('s002','tod22','GeneralOcean',",
"INSERT INTO \"CapacityFactorTech\" VALUES ('s002','tod23','GeneralOcean',",
"INSERT INTO \"CapacityFactorTech\" VALUES ('s002','tod24','GeneralOcean',",
"INSERT INTO \"CapacityFactorTech\" VALUES ('s003','tod01','GeneralOcean',",
"INSERT INTO \"CapacityFactorTech\" VALUES ('s003','tod02','GeneralOcean',",
"INSERT INTO \"CapacityFactorTech\" VALUES ('s003','tod03','GeneralOcean',",
"INSERT INTO \"CapacityFactorTech\" VALUES ('s003','tod04','GeneralOcean',",
"INSERT INTO \"CapacityFactorTech\" VALUES ('s003','tod05','GeneralOcean',",
"INSERT INTO \"CapacityFactorTech\" VALUES ('s003','tod06','GeneralOcean',",
"INSERT INTO \"CapacityFactorTech\" VALUES ('s003','tod07','GeneralOcean',",
"INSERT INTO \"CapacityFactorTech\" VALUES ('s003','tod08','GeneralOcean',",
"INSERT INTO \"CapacityFactorTech\" VALUES ('s003','tod09','GeneralOcean',",
"INSERT INTO \"CapacityFactorTech\" VALUES ('s003','tod10','GeneralOcean',",
"INSERT INTO \"CapacityFactorTech\" VALUES ('s003','tod11','GeneralOcean',",
"INSERT INTO \"CapacityFactorTech\" VALUES ('s003','tod12','GeneralOcean',",
"INSERT INTO \"CapacityFactorTech\" VALUES ('s003','tod13','GeneralOcean',",
"INSERT INTO \"CapacityFactorTech\" VALUES ('s003','tod14','GeneralOcean',",
"INSERT INTO \"CapacityFactorTech\" VALUES ('s003','tod15','GeneralOcean',",
"INSERT INTO \"CapacityFactorTech\" VALUES ('s003','tod16','GeneralOcean',",
"INSERT INTO \"CapacityFactorTech\" VALUES ('s003','tod17','GeneralOcean',",
"INSERT INTO \"CapacityFactorTech\" VALUES ('s003','tod18','GeneralOcean',",
"INSERT INTO \"CapacityFactorTech\" VALUES ('s003','tod19','GeneralOcean',",
"INSERT INTO \"CapacityFactorTech\" VALUES ('s003','tod20','GeneralOcean',",
"INSERT INTO \"CapacityFactorTech\" VALUES ('s003','tod21','GeneralOcean',",
"INSERT INTO \"CapacityFactorTech\" VALUES ('s003','tod22','GeneralOcean',",
"INSERT INTO \"CapacityFactorTech\" VALUES ('s003','tod23','GeneralOcean',",
"INSERT INTO \"CapacityFactorTech\" VALUES ('s003','tod24','GeneralOcean',",
"INSERT INTO \"CapacityFactorTech\" VALUES ('s004','tod01','GeneralOcean',",
"INSERT INTO \"CapacityFactorTech\" VALUES ('s004','tod02','GeneralOcean',",
"INSERT INTO \"CapacityFactorTech\" VALUES ('s004','tod03','GeneralOcean',",
"INSERT INTO \"CapacityFactorTech\" VALUES ('s004','tod04','GeneralOcean',",
"INSERT INTO \"CapacityFactorTech\" VALUES ('s004','tod05','GeneralOcean',",
"INSERT INTO \"CapacityFactorTech\" VALUES ('s004','tod06','GeneralOcean',",
"INSERT INTO \"CapacityFactorTech\" VALUES ('s004','tod07','GeneralOcean',",
"INSERT INTO \"CapacityFactorTech\" VALUES ('s004','tod08','GeneralOcean',",
"INSERT INTO \"CapacityFactorTech\" VALUES ('s004','tod09','GeneralOcean',",
"INSERT INTO \"CapacityFactorTech\" VALUES ('s004','tod10','GeneralOcean',",
"INSERT INTO \"CapacityFactorTech\" VALUES ('s004','tod11','GeneralOcean',",
"INSERT INTO \"CapacityFactorTech\" VALUES ('s004','tod12','GeneralOcean',",
"INSERT INTO \"CapacityFactorTech\" VALUES ('s004','tod13','GeneralOcean',",
"INSERT INTO \"CapacityFactorTech\" VALUES ('s004','tod14','GeneralOcean',",
"INSERT INTO \"CapacityFactorTech\" VALUES ('s004','tod15','GeneralOcean',",
"INSERT INTO \"CapacityFactorTech\" VALUES ('s004','tod16','GeneralOcean',",
"INSERT INTO \"CapacityFactorTech\" VALUES ('s004','tod17','GeneralOcean',",
"INSERT INTO \"CapacityFactorTech\" VALUES ('s004','tod18','GeneralOcean',",
"INSERT INTO \"CapacityFactorTech\" VALUES ('s004','tod19','GeneralOcean',",
"INSERT INTO \"CapacityFactorTech\" VALUES ('s004','tod20','GeneralOcean',",
"INSERT INTO \"CapacityFactorTech\" VALUES ('s004','tod21','GeneralOcean',",
"INSERT INTO \"CapacityFactorTech\" VALUES ('s004','tod22','GeneralOcean',",
"INSERT INTO \"CapacityFactorTech\" VALUES ('s004','tod23','GeneralOcean',",
"INSERT INTO \"CapacityFactorTech\" VALUES ('s004','tod24','GeneralOcean',"]


Text_CF_R=[
",'#Victor Ocean 2021');",
",'#Victor Ocean 2021');",
",'#Victor Ocean 2021');",
",'#Victor Ocean 2021');",
",'#Victor Ocean 2021');",
",'#Victor Ocean 2021');",
",'#Victor Ocean 2021');",
",'#Victor Ocean 2021');",
",'#Victor Ocean 2021');",
",'#Victor Ocean 2021');",
",'#Victor Ocean 2021');",
",'#Victor Ocean 2021');",
",'#Victor Ocean 2021');",
",'#Victor Ocean 2021');",
",'#Victor Ocean 2021');",
",'#Victor Ocean 2021');",
",'#Victor Ocean 2021');",
",'#Victor Ocean 2021');",
",'#Victor Ocean 2021');",
",'#Victor Ocean 2021');",
",'#Victor Ocean 2021');",
",'#Victor Ocean 2021');",
",'#Victor Ocean 2021');",
",'#Victor Ocean 2021');",
",'#Victor Ocean 2021');",
",'#Victor Ocean 2021');",
",'#Victor Ocean 2021');",
",'#Victor Ocean 2021');",
",'#Victor Ocean 2021');",
",'#Victor Ocean 2021');",
",'#Victor Ocean 2021');",
",'#Victor Ocean 2021');",
",'#Victor Ocean 2021');",
",'#Victor Ocean 2021');",
",'#Victor Ocean 2021');",
",'#Victor Ocean 2021');",
",'#Victor Ocean 2021');",
",'#Victor Ocean 2021');",
",'#Victor Ocean 2021');",
",'#Victor Ocean 2021');",
",'#Victor Ocean 2021');",
",'#Victor Ocean 2021');",
",'#Victor Ocean 2021');",
",'#Victor Ocean 2021');",
",'#Victor Ocean 2021');",
",'#Victor Ocean 2021');",
",'#Victor Ocean 2021');",
",'#Victor Ocean 2021');",
",'#Victor Ocean 2021');",
",'#Victor Ocean 2021');",
",'#Victor Ocean 2021');",
",'#Victor Ocean 2021');",
",'#Victor Ocean 2021');",
",'#Victor Ocean 2021');",
",'#Victor Ocean 2021');",
",'#Victor Ocean 2021');",
",'#Victor Ocean 2021');",
",'#Victor Ocean 2021');",
",'#Victor Ocean 2021');",
",'#Victor Ocean 2021');",
",'#Victor Ocean 2021');",
",'#Victor Ocean 2021');",
",'#Victor Ocean 2021');",
",'#Victor Ocean 2021');",
",'#Victor Ocean 2021');",
",'#Victor Ocean 2021');",
",'#Victor Ocean 2021');",
",'#Victor Ocean 2021');",
",'#Victor Ocean 2021');",
",'#Victor Ocean 2021');",
",'#Victor Ocean 2021');",
",'#Victor Ocean 2021');",
",'#Victor Ocean 2021');",
",'#Victor Ocean 2021');",
",'#Victor Ocean 2021');",
",'#Victor Ocean 2021');",
",'#Victor Ocean 2021');",
",'#Victor Ocean 2021');",
",'#Victor Ocean 2021');",
",'#Victor Ocean 2021');",
",'#Victor Ocean 2021');",
",'#Victor Ocean 2021');",
",'#Victor Ocean 2021');",
",'#Victor Ocean 2021');",
",'#Victor Ocean 2021');",
",'#Victor Ocean 2021');",
",'#Victor Ocean 2021');",
",'#Victor Ocean 2021');",
",'#Victor Ocean 2021');",
",'#Victor Ocean 2021');",
",'#Victor Ocean 2021');",
",'#Victor Ocean 2021');",
",'#Victor Ocean 2021');",
",'#Victor Ocean 2021');",
",'#Victor Ocean 2021');",
",'#Victor Ocean 2021');"]

CFixed_L=[
"INSERT INTO \"CostFixed\" VALUES (2017,'GeneralOcean',2017,",
"INSERT INTO \"CostFixed\" VALUES (2020,'GeneralOcean',2017,",
"INSERT INTO \"CostFixed\" VALUES (2025,'GeneralOcean',2017,",
"INSERT INTO \"CostFixed\" VALUES (2030,'GeneralOcean',2017,",
"INSERT INTO \"CostFixed\" VALUES (2020,'GeneralOcean',2020,",
"INSERT INTO \"CostFixed\" VALUES (2025,'GeneralOcean',2020,",
"INSERT INTO \"CostFixed\" VALUES (2030,'GeneralOcean',2020,",
"INSERT INTO \"CostFixed\" VALUES (2025,'GeneralOcean',2025,",
"INSERT INTO \"CostFixed\" VALUES (2030,'GeneralOcean',2025,",
"INSERT INTO \"CostFixed\" VALUES (2030,'GeneralOcean',2030,"]

CFixed_R=[
",'#M$/GWyr','#Victor Ocean 2021');",
",'#M$/GWyr','#Victor Ocean 2021');",
",'#M$/GWyr','#Victor Ocean 2021');",
",'#M$/GWyr','#Victor Ocean 2021');",
",'#M$/GWyr','#Victor Ocean 2021');",
",'#M$/GWyr','#Victor Ocean 2021');",
",'#M$/GWyr','#Victor Ocean 2021');",
",'#M$/GWyr','#Victor Ocean 2021');",
",'#M$/GWyr','#Victor Ocean 2021');",
",'#M$/GWyr','#Victor Ocean 2021');"]

CInvest_L=[
"INSERT INTO \"CostInvest\" VALUES ('GeneralOcean',2017,",
"INSERT INTO \"CostInvest\" VALUES ('GeneralOcean',2020,",
"INSERT INTO \"CostInvest\" VALUES ('GeneralOcean',2025,",
"INSERT INTO \"CostInvest\" VALUES ('GeneralOcean',2030,",
"INSERT INTO \"CostInvest\" VALUES ('GeneralOcean',2035,"]

CInvest_R=[
",'M$/GW','#Victor Ocean 2021');",
",'M$/GW','#Victor Ocean 2021');",
",'M$/GW','#Victor Ocean 2021');",
",'M$/GW','#Victor Ocean 2021');",
",'M$/GW','#Victor Ocean 2021');"]

